# Generated by Django 2.2.16 on 2023-01-27 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 27, 18, 38, 51, 538816, tzinfo=utc), verbose_name='date_of_pub'),
            preserve_default=False,
        ),
    ]
