# Generated by Django 2.2.16 on 2023-01-28 08:18

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230127_2314'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='author unique'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('author__lt', django.db.models.expressions.F('user')), ('author__gt', django.db.models.expressions.F('user')), _connector='OR'), name='dont subsctibe ypurself'),
        ),
    ]
